# PyTorch 基本运算示例

Torch的tensor和Numpy的Array，Pandas的Series和Dataframe类似，是了解应用这些代码库的基础，这里首先简单快速地了解Tensor及如何使用GPU，然后日常积累一些常用张量运算函数。

主要参考：

- [TENSORS](https://pytorch.org/tutorials/beginner/former_torchies/tensor_tutorial.html)
- [Speed Up your Algorithms Part 1 — PyTorch](https://towardsdatascience.com/speed-up-your-algorithms-part-1-pytorch-56d8a4ae7051)
- [PyTorch 101, Part 1: Understanding Graphs, Automatic Differentiation and Autograd](https://blog.paperspace.com/pytorch-101-understanding-graphs-and-automatic-differentiation/)

## 快速了解Tensor

pytorch作为NumPy的替代品，可以利用GPU的性能进行计算；可作为一个高灵活性、速度快的深度学习平台。

Tensor（张量）类似于NumPy的ndarray，但还可以在GPU上使用来加速计算。因此经常看到把numpy的数组包装为tensor再运算。tensor的操作和numpy中的数组操作类似，不再赘述，详见官网。下面列举一些简单例子。首先pytorch的导入是import torch，因为torch一直都是那个torch，一开始是别的语言写的，现在在python下，所以就叫pytorch。

In [1]:
import torch

Tensor是pytorch的基本数据类型：

In [2]:
x = torch.Tensor(5)
# 如果想要从tensor中获取到长度的int数据
type(list(x.shape)[0])

int

In [3]:
# 构建一个 5x3 的矩阵, 未初始化的:
x = torch.Tensor(5, 3)
x

tensor([[9.2755e-39, 1.0561e-38, 9.5510e-39],
        [1.0561e-38, 4.5919e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

pytorch中的一些基本运算：

In [4]:
# 构建一个随机初始化的矩阵:
x = torch.rand(5, 3)
x

tensor([[0.6500, 0.7761, 0.6299],
        [0.4548, 0.3825, 0.7434],
        [0.9794, 0.3191, 0.1690],
        [0.7228, 0.0245, 0.5472],
        [0.1111, 0.3976, 0.0551]])

In [5]:
x.size()

torch.Size([5, 3])

concatenate的操作使用torch.cat可以完成

In [6]:
x1 = torch.Tensor(1)
x2 = torch.Tensor(1)
torch.cat((x1,x2),0)

tensor([1.3823e+31, 2.3877e-38])

可以看到torch中的size也是torch中的类，包装了python的list，自然地，加减运算的对象也都是torch的tensor了。运算可以使用运算符，也可以使用函数。

In [7]:
# 加法
y = torch.rand(5, 3)
x + y

tensor([[0.8280, 1.6769, 1.0463],
        [0.5390, 1.0687, 1.1929],
        [1.6647, 0.6605, 1.1308],
        [1.6171, 0.6700, 0.7880],
        [1.0453, 1.3943, 0.8812]])

In [8]:
torch.add(x, y)

tensor([[0.8280, 1.6769, 1.0463],
        [0.5390, 1.0687, 1.1929],
        [1.6647, 0.6605, 1.1308],
        [1.6171, 0.6700, 0.7880],
        [1.0453, 1.3943, 0.8812]])

In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)

tensor([[0.8280, 1.6769, 1.0463],
        [0.5390, 1.0687, 1.1929],
        [1.6647, 0.6605, 1.1308],
        [1.6171, 0.6700, 0.7880],
        [1.0453, 1.3943, 0.8812]])

In [10]:
a = torch.ones(5)
a.add_(1)

tensor([2., 2., 2., 2., 2.])

numpy和tensor之间有很多类似的地方，比如索引，形状改变等：

In [11]:
# 可以用类似Numpy的索引来处理所有的张量！
x[:, 1]

tensor([0.7761, 0.3825, 0.3191, 0.0245, 0.3976])

In [12]:
# 改变大小: 如果你想要去改变tensor的大小, 可以使用 torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1就是让pytorch自己根据其他的维度去判断这里该是几维
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.6274, -1.2660,  1.3102,  1.9275],
        [-0.7556,  0.4957,  2.2412,  0.6251],
        [-0.5370,  2.1314, -0.0755,  0.4169],
        [-0.4280,  0.4309, -0.4394, -0.7138]])
tensor([-0.6274, -1.2660,  1.3102,  1.9275, -0.7556,  0.4957,  2.2412,  0.6251,
        -0.5370,  2.1314, -0.0755,  0.4169, -0.4280,  0.4309, -0.4394, -0.7138])
tensor([[-0.6274, -1.2660,  1.3102,  1.9275, -0.7556,  0.4957,  2.2412,  0.6251],
        [-0.5370,  2.1314, -0.0755,  0.4169, -0.4280,  0.4309, -0.4394, -0.7138]])


由于和numpy的紧密联系，因此pytorch的张量和numpy数组可以很方便的转换。

In [13]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

要注意numpy的array和torch的tensor转换后，数据是绑定的，如下所示：

In [15]:
# 看改变 np 数组之后 Torch Tensor 是如何自动改变的
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print("numpy的array：",a)
print("array转为torch的tensor：",b)
np.add(a, 1, out = a)
print(a)
print(b)

numpy的array： [1. 1. 1. 1. 1.]
array转为torch的tensor： tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [16]:
# 可以使用 .cuda 方法将 Tensors 在GPU上运行.
# 只要在  CUDA 是可用的情况下, 我们可以运行这段代码
if torch.cuda.is_available():
    b = b.cuda()
    print(b + b)

CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换。

张量要在GPU上计算，需要主动从CPU移动到GPU上。张量可以使用.to方法移动到任何设备（device）上

In [17]:
x = torch.randn(1)
print(x)
print(x.item())
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([0.9377])
0.937736451625824


## GPU or CPU

检查 cuda 设备是否可用：

In [18]:
import torch
torch.cuda.is_available()

True

In [19]:
# 如果有GPU的话 可以执行下面几个注释掉的代码
# torch.cuda.current_device()

In [20]:
# torch.cuda.get_device_name(0)

In [21]:
# Returns the current GPU memory usage by tensors in bytes for a given device
# torch.cuda.memory_allocated()

In [22]:
# Returns the current GPU memory managed by the caching allocator in bytes for a given device
# torch.cuda.memory_reserved()

In [23]:
# Releases all unoccupied cached memory currently held by the caching allocator so that those can be used in other GPU application and visible in nvidia-smi
# torch.cuda.empty_cache()

如何使用GPU？

如果像存储数据到CPU，那么简单定义即可：

In [24]:
a = torch.DoubleTensor([1., 2.])

这时候变量在CPU上，且后续的运算都会在CPU上，为了将数据转移到GPU上，需要使用 .cuda

In [25]:
# a = torch.FloatTensor([1., 2.]).cuda()

或者

In [26]:
# a = torch.cuda.FloatTensor([1., 2.])

这时候数据就在GPU上。模型同样可以转移到GPU上，比如：

In [27]:
from torch import nn
model = nn.Sequential(
         nn.Linear(20, 20),
         nn.ReLU(),
         nn.Linear(20, 4),
         nn.Softmax()
)
# model = model.cuda()

检查在不在GPU上。

In [28]:
next(model.parameters()).is_cuda

False

如果有多个GPU，可以使用Data Parallelism，拆分数据，将 Data Generator 拆分到更小的mini batches，然后送到多个GPUs

PyTorch中，并行通过torch.nn.DataParallel实现。一些关键函数：：

- Replicate：Module在多个设备上复制。
- Scatter：input在这些设备的第一维中分布。
- Gather：从这些设备收集input和连接第一维。
- parallel_apply：将从Scatter获得的一组输入分布式应用于从Replicate获得的相应的分布式Modules。

```Python
# Replicate module to devices in device_ids
replicas = nn.parallel.replicate(module, device_ids)
# Distribute input to devices in device_ids
inputs = nn.parallel.scatter(input, device_ids)
# Apply the models to corresponding inputs
outputs = nn.parallel.parallel_apply(replicas, inputs)
# Gather result from all devices to output_device
result = nn.parallel.gather(outputs, output_device)
```

或者一种更简单的方式：

```Python
model = nn.DataParallel(model, device_ids=device_ids)
result = model(input)
```

更多信息可以关注：

- [Multi-GPU Framework Comparisons](https://medium.com/@iliakarmanov/multi-gpu-rosetta-stone-d4fa96162986)
- [ilkarman/DeepLearningFrameworks](https://github.com/ilkarman/DeepLearningFrameworks)

下面是Tensor的常见计算，日常积累。

## 基本算术运算

Tensor是一种数据结构，是 PyTorch 的基本构建块。Tensors 非常像 numpy 数组，与 numpy 不同的是，张量旨在利用 GPU 的并行计算能力。许多 Tensor 语法类似于 numpy 数组的语法。

In [18]:
import numpy as np
import torch

### 初始化

直接调用Tensor即可完成初始化。

In [19]:
tt = torch.Tensor(3)

和numpy不同的是，为了完成梯度下降等优化计算，Tensor还有梯度相关的属性（后续文本会有更多介绍），初始化时候requires_grad默认是False

In [20]:
tt.requires_grad

False

初始化为0

In [21]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

Tensor

In [22]:
t_one = torch.ones(4)
t_one.requires_grad

False

requires_grad具有传染性。这意味着当通过对其他Tensors运算创建一个Tensor，且其中至少有一个用于创建的张量requires_grad被设置为True时，运算结果Tensor的requires_grad也将被设置为True。

In [23]:
a = torch.randn((3,3), requires_grad = True)
w1 = torch.randn((3,3))
b = w1*a 
b.requires_grad

True

如果想要计算后的张量不被前序变量传染，可以使用detach()（非inplace运算），先detach()再计算即可。

In [24]:
b_detach = w1*(a.detach())
b_detach == b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [25]:
b_detach.requires_grad

False

detach()不是inplace运算，所以a还是有requires_grad的。

In [26]:
a.requires_grad

True

### 均值计算

In [27]:
X = np.random.rand(6,4)
print(X,X.shape)
avg_np, _ = np.average(X, axis=0, returned=True)
avg_np, _

[[0.45003601 0.97489784 0.62049398 0.09110269]
 [0.40026833 0.85759564 0.68546586 0.27271109]
 [0.88953855 0.26980388 0.46891119 0.7821735 ]
 [0.07011137 0.85454264 0.09227025 0.40843787]
 [0.56613465 0.39923638 0.829733   0.04183137]
 [0.17818573 0.57736378 0.49219906 0.89792548]] (6, 4)


(array([0.42571244, 0.65557336, 0.53151222, 0.415697  ]),
 array([6., 6., 6., 6.]))

In [28]:
X_th = torch.tensor(X)
avg_th = torch.mean(X_th, dim=0)
avg_th

tensor([0.4257, 0.6556, 0.5315, 0.4157], dtype=torch.float64)

In [29]:
assert (X == X_th.numpy()).all()
# assert (avg_np == avg_th.numpy()).all()   # this fails alread

### 求和计算

求和运算和平均运算类似：

In [30]:
ta=torch.ones(5)
tc=torch.sum(ta)
tc

tensor(5.)

### 幂次计算

PyTorch下张量进行幂次计算需要使用 torch.pow 函数

In [31]:
import torch
a = torch.randn(4)
a

tensor([ 1.1996,  0.6044, -1.0557, -0.4547])

In [32]:
torch.pow(a, 2)

tensor([1.4389, 0.3653, 1.1146, 0.2067])

In [33]:
torch.pow(a, torch.Tensor([2]))

tensor([1.4389, 0.3653, 1.1146, 0.2067])

### PyTorch中的广播

试试torch的广播功能：

In [34]:
t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2=torch.sqrt(t1)

In [35]:
t1/((t2+0.1)**2)

tensor([[0.8264, 0.8723, 0.8938],
        [0.9070, 0.9162, 0.9231]])

### element-wise运算

In [36]:
ta=torch.ones(5)
tb=torch.zeros(5)
ta-tb

tensor([1., 1., 1., 1., 1.])

In [37]:
z = torch.FloatTensor([2]).repeat(1,5)
z

tensor([[2., 2., 2., 2., 2.]])

In [38]:
z/ta

tensor([[2., 2., 2., 2., 2.]])

In [39]:
td=ta/z
td

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])

In [40]:
te=td**2
te

tensor([[0.2500, 0.2500, 0.2500, 0.2500, 0.2500]])

In [41]:
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)

In [42]:
exp

tensor([1., 2., 3., 4.])

In [43]:
a

tensor([1., 2., 3., 4.])

In [44]:
torch.pow(a, exp)

tensor([  1.,   4.,  27., 256.])

看看二维的情况：

In [45]:
t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2=t1.repeat(1,4).view(-1, 3)
t2

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

In [46]:
t3 = torch.FloatTensor([[7,8,9],[10,11,12]])
t4=t3.repeat(1,4).view(-1, 3)
t4

tensor([[ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [10., 11., 12.],
        [10., 11., 12.],
        [10., 11., 12.]])

In [47]:
SST = (t4 - t2) ** 2
SST

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]])

In [48]:
SST=torch.sum(SST,dim=0)
SST

tensor([288., 288., 288.])

### 比较大小

两个张量，element-wise比较大小

In [49]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))
torch.maximum(a, b)

tensor([3, 2, 4])

如果张量大小不同，也会默认执行广播运算

In [50]:
a = torch.tensor((1, 2, -1))
b = torch.tensor([0])
torch.maximum(a, b)

tensor([1, 2, 0])

### 处理NaN值

有时候会有一nan值需要处理。在torch中检测是否有nan值可以使用：x != x

In [51]:
print(np.nan==np.nan)

False


In [52]:
t5 = torch.FloatTensor([[7,np.nan,9],[10,11,12]])
t5

tensor([[ 7., nan,  9.],
        [10., 11., 12.]])

如果是直接判断一个多维张量是否有nan值，可以使用：

In [53]:
mask= t5==t5
mask

tensor([[ True, False,  True],
        [ True,  True,  True]])

In [54]:
if len(mask[mask == True]) > 0:
    print("please check")

please check


In [55]:
t6=t5[mask]
t6

tensor([ 7.,  9., 10., 11., 12.])

为了让一般的数值计算能够成为梯度可追踪的计算，我们有时候需要将常见的一些计算用tensor重写，下面是NSE的例子：

In [56]:
def nse_2d(t,p):
    seq_length = t.shape[0]
    Ngage = t.shape[1]
    tmean = torch.mean(t, dim=0)
    tmeans = tmean.repeat(seq_length, 1)
    SST = torch.sum((t - tmeans) ** 2, dim=0)
    SSRes = torch.sum((t - p) ** 2, dim=0)
    # Same as Fredrick 2019
    # temp = SSRes / ((torch.sqrt(SST) + 0.1) ** 2)
    # original NSE
    temp = SSRes / SST
    loss = torch.sum(temp) / Ngage
    return loss

t1 = torch.FloatTensor([[1,2,3],[4,5,6]])
t2 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(nse_2d(t1,t2))

tensor(0.)


## 对Tensor的操作

In [57]:
import torch

### 复制操作

类似numpy的repeat和tile，torch中可以使用repeat：

In [58]:
z = torch.FloatTensor([[1,2,3],[4,5,6]])
z.repeat(1,4)

tensor([[1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6.]])

In [59]:
z.repeat(1,4).view(-1, 3)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

In [60]:
z.repeat(4,1)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.],
        [1., 2., 3.],
        [4., 5., 6.]])

In [61]:
x = torch.randn(2, 3, 4)
x

tensor([[[-0.9436, -0.7028,  0.0103, -1.0038],
         [ 0.5544,  0.4460, -1.0549, -0.4126],
         [ 0.9392, -1.1895, -1.6707, -0.2637]],

        [[ 1.1112,  0.8791,  2.0294,  0.6844],
         [ 0.4926, -0.2633,  1.7268, -0.2183],
         [-0.6889,  0.2896,  0.9341,  1.2021]]])

In [62]:
x[-1,:,:]

tensor([[ 1.1112,  0.8791,  2.0294,  0.6844],
        [ 0.4926, -0.2633,  1.7268, -0.2183],
        [-0.6889,  0.2896,  0.9341,  1.2021]])

In [63]:
x[-1,:,:].repeat(3,1,1)

tensor([[[ 1.1112,  0.8791,  2.0294,  0.6844],
         [ 0.4926, -0.2633,  1.7268, -0.2183],
         [-0.6889,  0.2896,  0.9341,  1.2021]],

        [[ 1.1112,  0.8791,  2.0294,  0.6844],
         [ 0.4926, -0.2633,  1.7268, -0.2183],
         [-0.6889,  0.2896,  0.9341,  1.2021]],

        [[ 1.1112,  0.8791,  2.0294,  0.6844],
         [ 0.4926, -0.2633,  1.7268, -0.2183],
         [-0.6889,  0.2896,  0.9341,  1.2021]]])

### 与numpy之间的转换

tensor 转换为numpy：

In [64]:
import torch
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [65]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [66]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


注意tensor变化时，array也会跟着变。反过来也一样：

In [67]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)  # see how changing the np array changed the torch Tensor automatically

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### 维度变换

再看看维度变换，三维变二维：

In [68]:
import torch
t1 = torch.FloatTensor([[[7,8,9],[10,11,12]],[[7,8,9],[10,11,12]]])
t1

tensor([[[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [69]:
t2=t1.view(-1, 3)
t2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [70]:
t3=t1.reshape(-1, 3)
t3

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

reshape 和 view 的区别这里简单补充下，参考了：[Pytorch-reshape与view的区别](https://congluwen.top/2018/12/pytorch_reshape_view/)。Pytorch中reshape()与view()都可以改变Tensor的shape但是有略微的区别.

- view()只可以由torch.Tensor.view()来调用，view():
    - 不改变Tensor数据，改变Tensor的size(即shape)
    - 对于一个将要被view的Tensor，新的size必须与原来的size与stride兼容,即新的维度必须是以下两种情况: 
        - 是原有维度的一个子空间
        - 只跨越原有满足邻接条件，stride[i]=stride[i+1]×size[i+1]的原有维度d,d+1,…,d+k\
    - 否则，在view之前必须调用contiguous()方法，对于该方法的讨论，见[StackOverflow](https://stackoverflow.com/questions/48915810/pytorch-contiguous)
- reshape()可以由torch.reshape(),也可由torch.Tensor.reshape()调用。reshape():
    - 同样也是返回与input数据量相同，但形状不同的tensor
    - 若满足view的条件，则不会copy，若不满足，则会copy

### 张量转置

In [71]:
import torch
x = torch.randn(2, 3)
x

tensor([[ 0.7203,  0.3192,  1.4156],
        [-0.2007,  0.3821, -0.2626]])

In [72]:
torch.t(x)

tensor([[ 0.7203, -0.2007],
        [ 0.3192,  0.3821],
        [ 1.4156, -0.2626]])

### 列表拼接

使用torch.cat可以实现列表的拼接。

In [1]:
import torch

tensor_lst = [torch.randn(2, 3, 1), torch.randn(2, 3, 1)]
torch.cat(tensor_lst, dim=-1).shape

torch.Size([2, 3, 2])

###  sparse update 操作

主要基于 [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter) 来实现 scatter散点 和 segment分段 等操作。散点和分段操作可以粗略地描述为基于给定的 "组-索引"张量的 reduce 操作。分段操作需要对 "组-索引 "张量进行排序，而散点操作则不受这些要求的限制。

安装：

```Shell
conda install pytorch-scatter -c pyg
```

pytorch_scatter中包含的所有操作都是可广播的，能在不同的数据类型上工作，在CPU和GPU上都有相应的后向实现，并且是完全可追踪的。

In [9]:
from torch_scatter import scatter

src = torch.randn(10, 6, 64)
index = torch.tensor([0, 1, 0, 1, 2, 1])

# Broadcasting in the first and last dim.
out = scatter(src, index, dim=1, reduce="sum")

print(out.size())

torch.Size([10, 3, 64])


上面的操作是类似下图这样的：

![](img/add.svg)

即有相同index号的一起执行同一种运算。

另一种类似的操作 Segment COO：

![](img/segment_coo.svg)

通过顺序的编号，将张量切分成几个组别，比如下面的例子，顺序分成了三组 0和0第一组，接下来三个1是第二组，最后2一组。

In [13]:
from torch_scatter import segment_coo

index = torch.tensor([0, 0, 1, 1, 1, 2])
index = index.view(1, -1)  # Broadcasting in the first and last dim.

out1 = segment_coo(src, index, reduce="sum")

print(out1.size())

torch.Size([10, 3, 64])


最后一种类似的操作：

In [14]:
from torch_scatter import segment_csr

indptr = torch.tensor([0, 2, 5, 6])
indptr = indptr.view(1, -1)  # Broadcasting in the first and last dim.

out2 = segment_csr(src, indptr, reduce="sum")

print(out2.size())

torch.Size([10, 3, 64])


indptr是指定了 0-2，2-5，5-6 的三个范围。

当然以上例子也都不是必须选择全部范围：

In [15]:
indptr = torch.tensor([2, 5, 6])
indptr = indptr.view(1, -1)  # Broadcasting in the first and last dim.

out2 = segment_csr(src, indptr, reduce="sum")
print(out2.size())

torch.Size([10, 2, 64])


试试别的维度，比如第一个维度

In [18]:
indptr1 = torch.tensor([2, 5, 6])
out3 = segment_csr(src, indptr1, reduce="sum")
print(out3.size())

torch.Size([2, 6, 64])


可以看到如果一维数组直接指定，就是在dim=0上操作，而之前的indptr是二维数组，就是在第二维上操作的

In [17]:
indptr

tensor([[2, 5, 6]])

再试试第三维：

In [19]:
indptr2 = indptr1.view(1, 1, -1)
out4 = segment_csr(src, indptr2, reduce="sum")
print(out4.size())

torch.Size([10, 6, 2])


如果不想要广播，各列的所取范围不同，那就得循环每列一个来算了，比如：

In [21]:
import numpy as np

t1 = torch.Tensor(np.arange(24).reshape(4,3,2))
t1

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]],

        [[18., 19.],
         [20., 21.],
         [22., 23.]]])

目标是最后一个维度根据索引做reduce操作，但是要求是最后一个维度第一组不做操作，第二组才做，然后是第一个维度的索引来reduce，但是第二维度上每个索引号不同，比如现在第二维度共三项，假设就是三种不同索引号，i1 = [0,1,3], i2 = [0,2,3], i3 = [0,3]，那么：

In [27]:
i1 = torch.tensor([0,1,3])
i2 = torch.tensor([0,1,2])
i3 = torch.tensor([2,3])
i_lst = [i1, i2, i3]

segs = []
for k in range(t1.shape[-1]):
    if k > 0:
        for j in range(t1.shape[1]):
            tjk = t1[:,j,k]
            segs.append(segment_csr(tjk, i_lst[j], reduce="sum"))

segs

[tensor([ 1., 20.]), tensor([3., 9.]), tensor([17.])]

In [28]:
t1[:,0,1]

tensor([ 1.,  7., 13., 19.])

In [29]:
t1[:,1,1]

tensor([ 3.,  9., 15., 21.])

In [30]:
t1[:,2,1]

tensor([ 5., 11., 17., 23.])

核对下，可以发现没有问题。